version: '3.9'

services:
  #---------------------------------------------------------------
  # POSTGRES 
  #---------------------------------------------------------------
  psql:
    container_name: postgres
    image: postgres:15.3-bullseye
    command: postgres -c 'max_connections=500'
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

    env_file:
      - ./dotenv/.env
