# Generated by Django 4.2.3 on 2023-07-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='number')),
                ('exp_date', models.DateField(verbose_name='exp_date')),
                ('holder', models.CharField(max_length=30, verbose_name='holder')),
                ('cvv', models.CharField(blank=True, max_length=4, null=True, verbose_name='cvv')),
                ('brand', models.CharField(max_length=10, verbose_name='brand')),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credita Cards',
            },
        ),
    ]
